// Generated by CoffeeScript 1.4.0
(function() {

  $(document).ready(function() {
    var ctx, fat, tall;
    ctx = $("#art")[0].getContext("2d");
    ctx.fillStyle = "#000000";
    fat = $(document).width();
    tall = $(document).height();
    return ctx.fillRect(0, 0, fat, tall);
  });

}).call(this);
